### ISSUE TITLE
installation docs for Windows

### ISSUE THREAD

**Issue by Bhupesh-V** [Bhupesh-V/ugit#20]
ugit should work on Windows considering we have either git bash installed or WSL working with the FZF binary.
It would be nice to have docs to install ugit the correct way.

Any help/suggestions are appreciated 💙

**Comment by thecesrom** [comment]
Since `ugit` relies upon `fzf` there is one small issue when Git Bash is used under Windows (not WSL).


```bash
$ mkdir ~/git-repo
$ cd ~/git-repo/
$ git init
Initialized empty Git repository in C:/Users/thecesrom/git-repo/.git/
$ ugit
Undo your last oopsie in Git 🙈️
Press ctrl+c to exit anytime
--height option is currently not supported on this platform
```

And while `fzf`'s wiki page for Windows suggests installing under WSL ([here](https://github.com/junegunn/fzf/wiki/Windows)), I have had success running Git Bash from the Windows Terminal.

Git Bash:
![git-bash](https://user-images.githubusercontent.com/19418023/155222155-8a8aa4dd-0cdd-4adc-8813-dbdf1c5399e4.png)

Git Bash under Windows Terminal:
![git-bash-wt](https://user-images.githubusercontent.com/19418023/155222201-be3af212-fd84-4454-81b4-6b2c183cbda6.png)

Not sure how you feel about adding a full section on how to install on Windows with Windows Terminal as a prerequisite.

My setup is not too complex.

- Windows Terminal
- Git Bash
- `fzf`
- `ugit`

**Comment by Bhupesh-V** [comment]
Hey thanks for mentioning this
I think if ugit works with Windows terminal out of the box, we can just recommend uses to use, Git bash inside windows terminal instead of it own one

**Comment by thecesrom** [comment]
Yes, Windows Terminal is the way to go for a non-WSL setup in Windows.

**Comment by Bhupesh-V** [comment]
Perfect, Can you also tell me how did you manage to install ugit on windows?
Does the `curl` version work? or is it something else

We need to have a basic setup in place for Windows users. Also, what do you think about [publishing to winget](https://docs.microsoft.com/en-us/windows/package-manager/package/https://docs.microsoft.com/en-us/windows/package-manager/package/)

**Comment by thecesrom** [comment]
> Can you also tell me how did you manage to install ugit on windows?

I already had installed Windows Terminal and Git, then I installed `fzf`. Here I will agree with you on leaving the installation of `fzf` up to the end-user.

> Does the `curl` version work?

Yes, I used the `curl` installation command for Linux and it worked just fine.

> Also, what do you think about [publishing to winget](https://docs.microsoft.com/en-us/windows/package-manager/package/)

Sure, if you can pull it off.

**Comment by vinayaknayar** [comment]
if no one is working on it, can you assign it to me?
